version: '3.1'
services:
    database:
        image: postgres
        restart: always
        environment: 
            POSTGRES_USER: flaskuser 
            POSTGRES_PASSWORD: 12345678
            POSTGRES_DB: flaskdata
        volumes:
          - data:/var/lib/postgresql/data
        
    myappli:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
          - database
        volumes:
          - .:/app
        ports:
          - 5000:5000
volumes:
    data:
